/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'FE' at '17-5-8 下午10:38' with Gradle 2.11
 *
 * @author FE, @date 17-5-8 下午10:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
